# Dependencies
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Glen Harmon'
tagline:          ''
description:      ''
url:              http://heyglen.github.io
baseurl:          ''

author:
  name:           'Glen Harmon'
  url:            ''

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/heyglen/heyglen.github.io

gems:
  - jemoji