# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Glen Harmon'
tagline:          ''
description:      ''
url:              http://heyglen.github.io
baseurl:          http://heyglen.github.io/

author:
  name:           'Glen Harmon'
  url:            ''

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/heyglen/heyglen.github.io         
