# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Glen Harmon'
tagline:          ''
description:      ''
url:              https://heyglen.github.io
baseurl:          https://github.com/heyglen/heyglen.github.io/

author:
  name:           'Glen Harmon'
  url:            ''

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/heyglen/heyglen.github.io         
