# Dependencies
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Glen Harmon Technical Blog'
tagline:          ''
description:      'Technical write-ups, tips and tricks'
url:              heyglen.github.io
baseurl:          ''

author:
  name:           'Glen Harmon'
  url:            ''

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/heyglen/heyglen.github.io

gems:
  - jemoji
  - jekyll-seo-tag

plugins:
  - jekyll-seo-tag

social:
  name: Glen Harmon
  links:
    - https://github.com/heyglen
    - https://dk.linkedin.com/in/glen-harmon-63580017